[build]
builder = "nixpacks"
buildCommand = "./mvnw clean package -DskipTests=true"

[deploy]
startCommand = "java -Djava.security.egd=file:/dev/./urandom -jar target/*.jar"
healthcheckEnabled = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10